const timeZones = [
  {
    id: "--0NlamEi",
    value: "Dateline Standard Time",
    offset: -12,
    text: "(UTC-12:00) International Date Line West",
  },
  {
    id: "Y2pJXCTGwL",
    value: "UTC-11",
    offset: -11,
    text: "(UTC-11:00) Coordinated Universal Time-11",
  },
  {
    id: "qD4Eht1d3B",
    value: "Hawaiian Standard Time",
    offset: -10,
    text: "(UTC-10:00) Hawaii",
  },
  {
    id: "WtbR_hv5gN",
    value: "Alaskan Standard Time",
    offset: -9,
    text: "(UTC-09:00) Alaska",
  },
  {
    id: "6XQyfuXRrG",
    value: "Pacific Standard Time (Mexico)",
    offset: -8,
    text: "(UTC-08:00) Baja California",
  },
  {
    id: "ixV-_TTCes",
    value: "Pacific Daylight Time",
    offset: -7,
    text: "(UTC-07:00) Pacific Daylight Time (US & Canada)",
  },
  {
    id: "iBm5CX8Wd6",
    value: "Pacific Standard Time",
    offset: -8,
    text: "(UTC-08:00) Pacific Standard Time (US & Canada)",
  },
  {
    id: "zpKzIr34a4",
    value: "US Mountain Standard Time",
    offset: -7,
    text: "(UTC-07:00) Arizona",
  },
  {
    id: "XLAoJPb5g7",
    value: "Mountain Standard Time (Mexico)",
    offset: -6,
    text: "(UTC-06:00) Chihuahua, La Paz, Mazatlan",
  },
  {
    id: "yhsTuMshim",
    value: "Mountain Standard Time",
    offset: -7,
    text: "(UTC-07:00) Mountain Time (US & Canada)",
  },
  {
    id: "XMo3-hgh88",
    value: "Central America Standard Time",
    offset: -6,
    text: "(UTC-06:00) Central America",
  },
  {
    id: "ixuAyV0P3b",
    value: "Central Standard Time",
    offset: -6,
    text: "(UTC-06:00) Central Time (US & Canada)",
  },
  {
    id: "Ktq6zszI2d",
    value: "Central Standard Time (Mexico)",
    offset: -6,
    text: "(UTC-06:00) Guadalajara, Mexico City, Monterrey",
  },
  {
    id: "ZwUH4JAkWg",
    value: "Canada Central Standard Time",
    offset: -6,
    text: "(UTC-06:00) Saskatchewan",
  },
  {
    id: "NjuCaALCeP",
    value: "SA Pacific Standard Time",
    offset: -5,
    text: "(UTC-05:00) Bogota, Lima, Quito",
  },
  {
    id: "rftcl7czKk",
    value: "Eastern Standard Time",
    offset: -5,
    text: "(UTC-05:00) Eastern Time (US & Canada)",
  },
  {
    id: "t3-zaTjfW1a",
    value: "Eastern Daylight Time",
    offset: -4,
    text: "(UTC-04:00) Eastern Daylight Time (US & Canada)",
  },
  {
    id: "jw2vwl-qsoS",
    value: "US Eastern Standard Time",
    offset: -5,
    text: "(UTC-05:00) Indiana (East)",
  },
  {
    id: "-TWOws5jibo",
    value: "Venezuela Standard Time",
    offset: -4.5,
    text: "(UTC-04:30) Caracas",
  },
  {
    id: "tR6g3J419ln",
    value: "Paraguay Standard Time",
    offset: -4,
    text: "(UTC-04:00) Asuncion",
  },
  {
    id: "p95ZVgiLhVo",
    value: "Atlantic Standard Time",
    offset: -4,
    text: "(UTC-04:00) Atlantic Time (Canada)",
  },
  {
    id: "7yaHGRhY6KN",
    value: "Central Brazilian Standard Time",
    offset: -4,
    text: "(UTC-04:00) Cuiaba",
  },
  {
    id: "or0MnRKSjTC",
    value: "SA Western Standard Time",
    offset: -4,
    text: "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
  },
  {
    id: "gYWpe52vXvX",
    value: "Pacific SA Standard Time",
    offset: -4,
    text: "(UTC-04:00) Santiago",
  },
  {
    id: "id9P6yKg3tc",
    value: "Newfoundland Standard Time",
    offset: -3.5,
    text: "(UTC-03:30) Newfoundland",
  },
  {
    id: "B3zO7POhO72",
    value: "E. South America Standard Time",
    offset: -3,
    text: "(UTC-03:00) Brasilia",
  },
  {
    id: "l3H8K5fXHRj",
    value: "Argentina Standard Time",
    offset: -3,
    text: "(UTC-03:00) Buenos Aires",
  },
  {
    id: "EZjbOGEJiqo",
    value: "SA Eastern Standard Time",
    offset: -3,
    text: "(UTC-03:00) Cayenne, Fortaleza",
  },
  {
    id: "nrIhaWBLLhP",
    value: "Greenland Standard Time",
    offset: -3,
    text: "(UTC-03:00) Greenland",
  },
  {
    id: "Bv9Ql8C_cWs",
    value: "Montevideo Standard Time",
    offset: -3,
    text: "(UTC-03:00) Montevideo",
  },
  {
    id: "H_JDC8w6FmH",
    value: "Bahia Standard Time",
    offset: -3,
    text: "(UTC-03:00) Salvador",
  },
  {
    id: "7Ovy0MX_RNX",
    value: "UTC-02",
    offset: -2,
    text: "(UTC-02:00) Coordinated Universal Time-02",
  },
  {
    id: "Lq13TpmE0zS",
    value: "Mid-Atlantic Standard Time",
    offset: -1,
    text: "(UTC-02:00) Mid-Atlantic - Old",
  },
  {
    id: "xBh0Hm51VnQ",
    value: "Azores Standard Time",
    offset: 0,
    text: "(UTC-01:00) Azores",
  },
  {
    id: "il_assB4YdB",
    value: "Cape Verde Standard Time",
    offset: -1,
    text: "(UTC-01:00) Cape Verde Is.",
  },
  {
    id: "iCEhNoClXi7",
    value: "Morocco Standard Time",
    offset: 1,
    text: "(UTC) Casablanca",
  },
  {
    id: "HV8Up9R1XVf",
    value: "UTC",
    offset: 0,
    text: "(UTC) Coordinated Universal Time",
  },
  {
    id: "N0qWAPX6BJA",
    value: "GMT Standard Time",
    offset: 0,
    text: "(UTC) Edinburgh, London",
  },
  {
    id: "AZkSpkgTRhB",
    value: "British Summer Time",
    offset: 1,
    text: "(UTC+01:00) Edinburgh, London",
  },
  {
    id: "wGcOg_tk-7G",
    value: "GMT Standard Time",
    offset: 0,
    text: "(UTC) Dublin, Lisbon",
  },
  {
    id: "1rd6XOIUPND",
    value: "Greenwich Standard Time",
    offset: 0,
    text: "(UTC) Monrovia, Reykjavik",
  },
  {
    id: "4YppiMYaKdJ",
    value: "W. Europe Standard Time",
    offset: 1,
    text: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  },
  {
    id: "gxGhRxp9m-w",
    value: "Central Europe Standard Time",
    offset: 2,
    text: "(UTC+02:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
  },
  {
    id: "AajNIg9uvch",
    value: "Romance Standard Time",
    offset: 1,
    text: "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
  },
  {
    id: "Dps7-_aEadV",
    value: "Central European Standard Time",
    offset: 2,
    text: "(UTC+02:00) Sarajevo, Skopje, Warsaw, Zagreb",
  },
  {
    id: "KsxAQ8XchKN",
    value: "W. Central Africa Standard Time",
    offset: 1,
    text: "(UTC+01:00) West Central Africa",
  },
  {
    id: "0eBDU0dkW5p",
    value: "Namibia Standard Time",
    offset: 1,
    text: "(UTC+01:00) Windhoek",
  },
  {
    id: "rOR6IMk9bng",
    value: "GTB Standard Time",
    offset: 2,
    text: "(UTC+02:00) Athens, Bucharest",
  },
  {
    id: "kLbhSo9RB24",
    value: "Middle East Standard Time",
    offset: 3,
    text: "(UTC+03:00) Beirut",
  },
  {
    id: "JmSM6ylRDCV",
    value: "Egypt Standard Time",
    offset: 2,
    text: "(UTC+02:00) Cairo",
  },
  {
    id: "-TRhCEGu2r9",
    value: "Syria Standard Time",
    offset: 3,
    text: "(UTC+03:00) Damascus",
  },
  {
    id: "NIf7MSlZxAW",
    value: "E. Europe Standard Time",
    offset: 2,
    text: "(UTC+02:00) E. Europe",
  },
  {
    id: "FZVKl7iuRdo",
    value: "South Africa Standard Time",
    offset: 2,
    text: "(UTC+02:00) Harare, Pretoria",
  },
  {
    id: "_DSquaayb4I",
    value: "FLE Standard Time",
    offset: 2,
    text: "(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
  },
  {
    id: "nAygbGpRVAh",
    value: "Turkey Standard Time",
    offset: 3,
    text: "(UTC+03:00) Istanbul",
  },
  {
    id: "KKn5oyB4XwR",
    value: "Israel Standard Time",
    offset: 3,
    text: "(UTC+03:00) Jerusalem",
  },
  {
    id: "4P61-3iE51c",
    value: "Libya Standard Time",
    offset: 2,
    text: "(UTC+02:00) Tripoli",
  },
  {
    id: "WuAlKgxoD1p",
    value: "Jordan Standard Time",
    offset: 3,
    text: "(UTC+03:00) Amman",
  },
  {
    id: "tLc4ausyES-",
    value: "Arabic Standard Time",
    offset: 3,
    text: "(UTC+03:00) Baghdad",
  },
  {
    id: "I92HU0ZajIh",
    value: "Kaliningrad Standard Time",
    offset: 2,
    text: "(UTC+02:00) Kaliningrad",
  },
  {
    id: "SGK1BGPrBNw",
    value: "Arab Standard Time",
    offset: 3,
    text: "(UTC+03:00) Kuwait, Riyadh",
  },
  {
    id: "u7YnTgJXx1n",
    value: "E. Africa Standard Time",
    offset: 3,
    text: "(UTC+03:00) Nairobi",
  },
  {
    id: "38Nuhyt7QjC",
    value: "Moscow Standard Time",
    offset: 3,
    text: "(UTC+03:00) Moscow, St. Petersburg, Volgograd, Minsk",
  },
  {
    id: "56lC-PBCCge",
    value: "Samara Time",
    offset: 4,
    text: "(UTC+04:00) Samara, Ulyanovsk, Saratov",
  },
  {
    id: "2UXvQGgykxe",
    value: "Iran Standard Time",
    offset: 3.5,
    text: "(UTC+03:30) Tehran",
  },
  {
    id: "VB3vIo4ae2Y",
    value: "Arabian Standard Time",
    offset: 4,
    text: "(UTC+04:00) Abu Dhabi, Muscat",
  },
  {
    id: "lTw0nz8m711",
    value: "Azerbaijan Standard Time",
    offset: 4,
    text: "(UTC+04:00) Baku",
  },
  {
    id: "5K76iaq2-t1",
    value: "Mauritius Standard Time",
    offset: 4,
    text: "(UTC+04:00) Port Louis",
  },
  {
    id: "f09pckgPRGo",
    value: "Georgian Standard Time",
    offset: 4,
    text: "(UTC+04:00) Tbilisi",
  },
  {
    id: "NDLas4LdrKN",
    value: "Caucasus Standard Time",
    offset: 4,
    text: "(UTC+04:00) Yerevan",
  },
  {
    id: "WnP7dMDZ5Gc",
    value: "Afghanistan Standard Time",
    offset: 4.5,
    text: "(UTC+04:30) Kabul",
  },
  {
    id: "MvlhwT3pPFk",
    value: "West Asia Standard Time",
    offset: 5,
    text: "(UTC+05:00) Ashgabat, Tashkent",
  },
  {
    id: "TzAk5qB028Y",
    value: "Yekaterinburg Time",
    offset: 5,
    text: "(UTC+05:00) Yekaterinburg",
  },
  {
    id: "uF6HBcC1cv8",
    value: "Pakistan Standard Time",
    offset: 5,
    text: "(UTC+05:00) Islamabad, Karachi",
  },
  {
    id: "U3Fu91gor6Y",
    value: "India Standard Time",
    offset: 5.5,
    text: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
  },
  {
    id: "_kSO6H9MUfw",
    value: "Sri Lanka Standard Time",
    offset: 5.5,
    text: "(UTC+05:30) Sri Jayawardenepura",
  },
  {
    id: "FZIqM_Mdp9A",
    value: "Nepal Standard Time",
    offset: 5.75,
    text: "(UTC+05:45) Kathmandu",
  },
  {
    id: "YrjvqXCMji5",
    value: "Central Asia Standard Time",
    offset: 6,
    text: "(UTC+06:00) Nur-Sultan (Astana)",
  },
  {
    id: "PwVtuVb78B0",
    value: "Bangladesh Standard Time",
    offset: 6,
    text: "(UTC+06:00) Dhaka",
  },
  {
    id: "pST5RaFkoei",
    value: "Myanmar Standard Time",
    offset: 6.5,
    text: "(UTC+06:30) Yangon (Rangoon)",
  },
  {
    id: "GateKDESF85",
    value: "SE Asia Standard Time",
    offset: 7,
    text: "(UTC+07:00) Bangkok, Hanoi, Jakarta",
  },
  {
    id: "duL5OEqPb1G",
    value: "N. Central Asia Standard Time",
    offset: 7,
    text: "(UTC+07:00) Novosibirsk",
  },
  {
    id: "2v4X2dODtRl",
    value: "China Standard Time",
    offset: 8,
    text: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
  },
  {
    id: "BMm0BZkg6gA",
    value: "North Asia Standard Time",
    offset: 8,
    text: "(UTC+08:00) Krasnoyarsk",
  },
  {
    id: "qjcyvKP-g-c",
    value: "Singapore Standard Time",
    offset: 8,
    text: "(UTC+08:00) Kuala Lumpur, Singapore",
  },
  {
    id: "PDcpfxSM1Tl",
    value: "W. Australia Standard Time",
    offset: 8,
    text: "(UTC+08:00) Perth",
  },
  {
    id: "oavFAUt85Li",
    value: "Taipei Standard Time",
    offset: 8,
    text: "(UTC+08:00) Taipei",
  },
  {
    id: "ukUHrC6sLpU",
    value: "Ulaanbaatar Standard Time",
    offset: 8,
    text: "(UTC+08:00) Ulaanbaatar",
  },
  {
    id: "W7HzdKCvAsP",
    value: "North Asia East Standard Time",
    offset: 8,
    text: "(UTC+08:00) Irkutsk",
  },
  {
    id: "lmnYjYxIYpD",
    value: "Japan Standard Time",
    offset: 9,
    text: "(UTC+09:00) Osaka, Sapporo, Tokyo",
  },
  {
    id: "VorVcgQOUd5",
    value: "Korea Standard Time",
    offset: 9,
    text: "(UTC+09:00) Seoul",
  },
  {
    id: "Doxyo9zrzfM",
    value: "Cen. Australia Standard Time",
    offset: 9.5,
    text: "(UTC+09:30) Adelaide",
  },
  {
    id: "AVpbDQMgaFy",
    value: "AUS Central Standard Time",
    offset: 9.5,
    text: "(UTC+09:30) Darwin",
  },
  {
    id: "8mH6_7S9ECM",
    value: "E. Australia Standard Time",
    offset: 10,
    text: "(UTC+10:00) Brisbane",
  },
  {
    id: "qn39cXQVzH4",
    value: "AUS Eastern Standard Time",
    offset: 10,
    text: "(UTC+10:00) Canberra, Melbourne, Sydney",
  },
  {
    id: "vNjcraj7FGi",
    offset: 10,
    text: "(UTC+10:00) Hobart",
  },
  {
    id: "YVBlEwbQ57T",
    value: "Yakutsk Standard Time",
    offset: 9,
    text: "(UTC+09:00) Yakutsk",
  },
  {
    id: "wqF2PkN7mPz",
    value: "Central Pacific Standard Time",
    offset: 11,
    text: "(UTC+11:00) Solomon Is., New Caledonia",
  },
  {
    id: "wQWalygaWP-",
    value: "Vladivostok Standard Time",
    offset: 11,
    text: "(UTC+11:00) Vladivostok",
  },
  {
    id: "i8nIowKjiit",
    value: "New Zealand Standard Time",
    offset: 12,
    text: "(UTC+12:00) Auckland, Wellington",
  },
  {
    id: "6_oWXDh8lq9",
    value: "UTC+12",
    offset: 12,
    text: "(UTC+12:00) Coordinated Universal Time+12",
  },
  {
    id: "QGF0AZpjnGk",
    value: "Fiji Standard Time",
    offset: 12,
    text: "(UTC+12:00) Fiji",
  },
  {
    id: "XbR5tZJB8tk",
    value: "Magadan Standard Time",
    offset: 12,
    text: "(UTC+12:00) Magadan",
  },
  {
    id: "1_Qyo2-vn_D",
    value: "Kamchatka Standard Time",
    offset: 13,
    text: "(UTC+12:00) Petropavlovsk-Kamchatsky - Old",
  },
  {
    id: "_M8jsw7LBUd",
    value: "Tonga Standard Time",
    offset: 13,
    text: "(UTC+13:00) Nuku'alofa",
  },
];

export default timeZones;
